name: 📺 Dailies

on:
  workflow_run:
    workflows: ["🎬 Render Pipeline"]
    types:
      - completed

jobs:
  dailies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg + Python
        run: |
          sudo apt update
          sudo apt install -y ffmpeg python3

      - name: Generate Shot List
        run: python3 scripts/combine.py

      - name: Create Dailies Video
        run: |
          mkdir -p dailies
          ffmpeg -f concat -safe 0 -i shots.txt \
          -c copy dailies/daily.mp4

      - name: Upload Dailies
        uses: actions/upload-artifact@v4
        with:
          name: dailies
          path: dailies/
